-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 09:27:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xintern
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xintern
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xintern` DEFAULT CHARACTER SET utf8 ;
USE `xintern` ;

-- -----------------------------------------------------
-- Table `xintern`.`xi_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_account` (
  `a_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `a_role` SMALLINT(3) UNSIGNED NULL,
  `a_phone` VARCHAR(15) NOT NULL,
  `a_unionId` VARCHAR(255) NULL,
  `a_openId` VARCHAR(255) NULL,
  `a_password` VARCHAR(255) NULL,
  `a_point` INT NULL DEFAULT 0,
  `a_balance` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`a_id`),
  UNIQUE INDEX `account_wechat` (`a_unionId` ASC),
  UNIQUE INDEX `account_phone` (`a_phone` ASC, `a_role` ASC),
  UNIQUE INDEX `a_openId_UNIQUE` (`a_openId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_student` (
  `s_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `s_accountid` BIGINT(64) UNSIGNED NOT NULL,
  `s_name` VARCHAR(45) NULL,
  `s_idno` VARCHAR(45) NULL,
  `s_phone` VARCHAR(15) NULL,
  `s_gender` TINYINT(1) NULL,
  `s_education` INT(3) UNSIGNED NULL COMMENT '0：大专\n1：本科\n2：硕士\n3：博士',
  `s_major` VARCHAR(45) NULL,
  `s_area` VARCHAR(45) NULL,
  `s_email` VARCHAR(45) NULL,
  `s_school` VARCHAR(45) NULL,
  `s_language` VARCHAR(45) NULL,
  `s_langlevel` INT(3) UNSIGNED NULL COMMENT '0: 一般\n1：良好\n2：熟练\n3：精通',
  `s_grade` INT(3) UNSIGNED NULL COMMENT '0: 一年级\n1：二年级\n…',
  `s_stucard` VARCHAR(255) NULL,
  `s_certs` VARCHAR(2000) NULL,
  `s_selfeval` TEXT(2000) NULL,
  `s_socialexp` TEXT(2000) NULL,
  `s_workexp` TEXT(2000) NULL,
  `s_fundscert` TINYINT(1) NULL,
  `s_securitiescert` TINYINT(1) NULL,
  `s_avatar` VARCHAR(255) NULL,
  `s_subscription` VARCHAR(500) NULL,
  `s_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `s_frozen` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`s_id`, `s_accountid`),
  INDEX `fk_student_account` (`s_accountid` ASC),
  CONSTRAINT `fk_xi_student_xi_account1`
    FOREIGN KEY (`s_accountid`)
    REFERENCES `xintern`.`xi_account` (`a_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_company` (
  `c_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_accountid` BIGINT(64) UNSIGNED NOT NULL,
  `c_name` VARCHAR(45) NULL,
  `c_addr` VARCHAR(255) NULL,
  `c_type` VARCHAR(45) NULL,
  `c_scale` VARCHAR(45) NULL,
  `c_contact` VARCHAR(45) NULL,
  `c_contactpos` VARCHAR(45) NULL,
  `c_contactphone` VARCHAR(45) NULL,
  `c_avatar` VARCHAR(255) NULL,
  `c_email` VARCHAR(45) NULL,
  `c_phone` VARCHAR(45) NULL,
  `c_industry` VARCHAR(45) NULL,
  `c_code` VARCHAR(45) NULL,
  `c_intro` TEXT(1000) NULL,
  `c_video` VARCHAR(255) NULL,
  `c_link` VARCHAR(255) NULL,
  `c_logo` VARCHAR(255) NULL,
  `c_cert` VARCHAR(255) NULL,
  `c_verified` TINYINT(1) NULL,
  `c_createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `c_priority` INT NULL DEFAULT 0,
  `c_score1` DECIMAL(3,2) UNSIGNED NULL,
  `c_score2` DECIMAL(3,2) UNSIGNED NULL,
  `c_score3` DECIMAL(3,2) UNSIGNED NULL,
  `c_score4` DECIMAL(3,2) UNSIGNED NULL,
  `c_score5` DECIMAL(3,2) UNSIGNED NULL,
  `c_frozen` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`c_id`, `c_accountid`),
  INDEX `fk_company_account` (`c_accountid` ASC),
  INDEX `i_company_verify` (`c_verified` ASC),
  CONSTRAINT `fk_xi_company_xi_account1`
    FOREIGN KEY (`c_accountid`)
    REFERENCES `xintern`.`xi_account` (`a_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_position` (
  `p_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `p_companyid` BIGINT(64) UNSIGNED NOT NULL,
  `p_title` VARCHAR(45) NULL,
  `p_ptype` VARCHAR(45) NULL,
  `p_area` VARCHAR(45) NULL,
  `p_addr` VARCHAR(255) NULL,
  `p_startdate` DATE NULL,
  `p_enddate` DATE NULL,
  `p_starttime` TIME NULL,
  `p_endtime` TIME NULL,
  `p_salary` INT UNSIGNED NULL COMMENT 'salary paid by company',
  `p_stusalary` INT UNSIGNED NULL COMMENT '扣除手续费后的工资',
  `p_unit` VARCHAR(45) NULL COMMENT 'salary unit',
  `p_mindays` INT UNSIGNED NULL COMMENT '每周最少工作天数',
  `p_continuous` TINYINT(1) NULL COMMENT '是否要求连续工作',
  `p_count` INT UNSIGNED NULL,
  `p_retention` TINYINT(1) NULL COMMENT '是否可留用',
  `p_intro` TEXT(1000) NULL,
  `p_reqgender` INT(1) UNSIGNED NULL COMMENT 'NULL: 不限\n0: male\n1: female',
  `p_reqedu` INT(3) UNSIGNED NULL,
  `p_reqgrade` INT(3) UNSIGNED NULL,
  `p_reqmajor` VARCHAR(45) NULL,
  `p_reqlang` VARCHAR(45) NULL,
  `p_reqlanglevel` INT(3) UNSIGNED NULL COMMENT '0: 一般\n1：良好\n2：熟练\n3：精通',
  `p_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `p_priority` INT NULL DEFAULT 0,
  `p_active` TINYINT(1) NULL,
  PRIMARY KEY (`p_id`, `p_companyid`),
  INDEX `refer_company_idx` (`p_companyid` ASC),
  INDEX `pos_active` (`p_active` ASC),
  CONSTRAINT `fk_position_belongs_to_company`
    FOREIGN KEY (`p_companyid`)
    REFERENCES `xintern`.`xi_company` (`c_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_resume` (
  `r_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `r_positionid` BIGINT(64) UNSIGNED NOT NULL,
  `r_stuid` BIGINT(64) UNSIGNED NOT NULL,
  `r_state` INT(4) UNSIGNED NULL,
  `r_salary` INT NULL,
  `r_stusalary` INT NULL,
  `r_interviewtime` DATETIME NULL,
  `r_interviewplace` VARCHAR(255) NULL,
  `r_unit` VARCHAR(45) NULL,
  `r_contact` VARCHAR(45) NULL,
  `r_contactphone` VARCHAR(45) NULL,
  `r_offerPlace` VARCHAR(45) NULL,
  `r_offerTime` DATETIME NULL,
  `r_commentstu` VARCHAR(255) NULL,
  `r_commentcomp` VARCHAR(255) NULL,
  `r_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `r_endtime` DATETIME NULL,
  PRIMARY KEY (`r_id`, `r_positionid`, `r_stuid`),
  INDEX `fk_resume_stu` (`r_stuid` ASC),
  INDEX `fk_resume_position` (`r_positionid` ASC),
  CONSTRAINT `fk_resume_positionid`
    FOREIGN KEY (`r_positionid`)
    REFERENCES `xintern`.`xi_position` (`p_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resume_stuid`
    FOREIGN KEY (`r_stuid`)
    REFERENCES `xintern`.`xi_student` (`s_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_news` (
  `n_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `n_title` VARCHAR(255) NULL,
  `n_content` TEXT(2000) NULL,
  `n_author` VARCHAR(45) NULL,
  `n_view` BIGINT(64) UNSIGNED NOT NULL DEFAULT 0,
  `n_star` BIGINT(64) UNSIGNED NOT NULL DEFAULT 0,
  `n_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `n_published` TINYINT(1) NULL DEFAULT 1,
  `n_priority` INT NULL DEFAULT 0,
  PRIMARY KEY (`n_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_pointlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_pointlog` (
  `p_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `p_accountid` BIGINT(64) UNSIGNED NULL,
  `p_type` SMALLINT(4) UNSIGNED NULL,
  `p_value` INT NULL,
  `p_refid` BIGINT(64) UNSIGNED NULL COMMENT '	',
  `p_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`p_id`),
  UNIQUE INDEX `POINT_UNIQUE` (`p_accountid` ASC, `p_type` ASC, `p_refid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_notification` (
  `n_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `n_accountid` BIGINT(64) UNSIGNED NULL,
  `n_type` SMALLINT(6) UNSIGNED NULL,
  `n_msg` VARCHAR(255) NULL,
  `n_refid` BIGINT(64) UNSIGNED NULL,
  `n_read` TINYINT(1) NULL DEFAULT 0,
  `n_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '	',
  PRIMARY KEY (`n_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_stuPosCollect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_stuPosCollect` (
  `c_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `c_stuid` BIGINT(64) UNSIGNED NOT NULL,
  `c_posid` BIGINT(64) UNSIGNED NOT NULL,
  PRIMARY KEY (`c_id`, `c_stuid`, `c_posid`),
  UNIQUE INDEX `stuposunique` (`c_stuid` ASC, `c_posid` ASC),
  INDEX `stuposstu` (`c_stuid` ASC),
  INDEX `stupospos` (`c_posid` ASC),
  CONSTRAINT `fk_xi_student_has_xi_position_xi_student1`
    FOREIGN KEY (`c_stuid`)
    REFERENCES `xintern`.`xi_student` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_xi_student_has_xi_position_xi_position1`
    FOREIGN KEY (`c_posid`)
    REFERENCES `xintern`.`xi_position` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_code` (
  `c_id` BIGINT(64) NOT NULL AUTO_INCREMENT,
  `c_phone` VARCHAR(45) NULL,
  `c_code` VARCHAR(45) NULL,
  `c_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`c_id`),
  INDEX `code_phone` (`c_phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_newsstar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_newsstar` (
  `s_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `s_accountid` BIGINT(64) UNSIGNED NULL,
  `s_newsid` BIGINT(64) UNSIGNED NULL,
  `s_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`s_id`),
  INDEX `newsstar_account_idx` (`s_accountid` ASC),
  INDEX `newsstar_news_idx` (`s_newsid` ASC),
  UNIQUE INDEX `nesstar_unique` (`s_accountid` ASC, `s_newsid` ASC),
  CONSTRAINT `newsstar_account`
    FOREIGN KEY (`s_accountid`)
    REFERENCES `xintern`.`xi_account` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `newsstar_news`
    FOREIGN KEY (`s_newsid`)
    REFERENCES `xintern`.`xi_news` (`n_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_rate` (
  `r_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `r_resumeid` BIGINT(64) UNSIGNED NULL,
  `r_companyid` BIGINT(64) UNSIGNED NULL,
  `r_stuid` BIGINT(64) UNSIGNED NULL,
  `r_direction` SMALLINT(1) UNSIGNED NULL,
  `r_score1` SMALLINT(4) UNSIGNED NULL,
  `r_score2` SMALLINT(4) UNSIGNED NULL,
  `r_score3` SMALLINT(4) UNSIGNED NULL,
  `r_score4` SMALLINT(4) UNSIGNED NULL,
  `r_score5` SMALLINT(4) UNSIGNED NULL,
  `r_comment` VARCHAR(255) NULL,
  `r_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`r_id`),
  INDEX `company_idx` (`r_companyid` ASC),
  INDEX `student_idx` (`r_stuid` ASC),
  INDEX `direction` (`r_direction` ASC),
  INDEX `resume_idx` (`r_resumeid` ASC),
  UNIQUE INDEX `unque` (`r_resumeid` ASC, `r_direction` ASC),
  CONSTRAINT `company`
    FOREIGN KEY (`r_companyid`)
    REFERENCES `xintern`.`xi_company` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student`
    FOREIGN KEY (`r_stuid`)
    REFERENCES `xintern`.`xi_student` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resume`
    FOREIGN KEY (`r_resumeid`)
    REFERENCES `xintern`.`xi_resume` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_meta` (
  `m_key` VARCHAR(255) NOT NULL,
  `m_value` TEXT(10000) NULL,
  PRIMARY KEY (`m_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_salary` (
  `s_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `s_resumeid` BIGINT(64) UNSIGNED NULL,
  `s_companyid` BIGINT(64) UNSIGNED NULL,
  `s_stuid` BIGINT(64) UNSIGNED NULL,
  `s_month` VARCHAR(20) NULL,
  `s_workdays` DOUBLE UNSIGNED NULL,
  `s_value` DOUBLE NULL,
  `s_stuValue` DOUBLE NULL,
  `s_stuComment` VARCHAR(255) NULL,
  `s_state` SMALLINT(2) UNSIGNED NULL DEFAULT 0,
  `s_createtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `s_paytime` DATETIME NULL,
  `s_updatetime` DATETIME NULL,
  PRIMARY KEY (`s_id`),
  INDEX `salary_resume_idx` (`s_resumeid` ASC),
  INDEX `salary_company_idx` (`s_companyid` ASC),
  INDEX `salary_student_idx` (`s_stuid` ASC),
  CONSTRAINT `salary_resume`
    FOREIGN KEY (`s_resumeid`)
    REFERENCES `xintern`.`xi_resume` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salary_company`
    FOREIGN KEY (`s_companyid`)
    REFERENCES `xintern`.`xi_company` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salary_student`
    FOREIGN KEY (`s_stuid`)
    REFERENCES `xintern`.`xi_student` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_feedback` (
  `f_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `f_accountId` BIGINT(64) UNSIGNED NULL,
  `f_content` VARCHAR(500) NULL,
  `f_state` SMALLINT(4) UNSIGNED NULL,
  `f_createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`f_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xintern`.`xi_withdraw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xintern`.`xi_withdraw` (
  `w_id` BIGINT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `w_accountId` BIGINT(64) UNSIGNED NULL,
  `w_value` DOUBLE UNSIGNED NULL,
  `w_channel` SMALLINT(4) UNSIGNED NULL,
  `w_state` SMALLINT(4) UNSIGNED NULL,
  `w_confirmed` TINYINT(1) NULL DEFAULT 0 COMMENT 'whether payment confirmed by channel',
  `w_createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `w_payTime` DATETIME NULL,
  PRIMARY KEY (`w_id`),
  INDEX `withdraw_fk_account_idx` (`w_accountId` ASC),
  CONSTRAINT `withdraw_fk_account`
    FOREIGN KEY (`w_accountId`)
    REFERENCES `xintern`.`xi_account` (`a_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE USER 'xintern'@'localhost' IDENTIFIED BY 'ddcreative';

GRANT ALL ON `xintern`.* TO 'xintern'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
